apiVersion: v1
kind: Pod
metadata:
  name: dockerhubsecretpod
  namespace: test-ns
spec:
  containers:
   - name: dockerhubsecret
     image: naresh74/newaravaimage
    # ports:
     # - containerPort: 8080
  imagePullSecrets:
  - name: dockerhubsecret
