apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
      metadata:
        name: javawebapppod
        labels:
          app: javawebapp
      spec:
        containers:
        - name: javawebapp
          image: dockerhandson/java-web-app:2
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
