apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: javawebapp
  template:
      metadata:
        name: javawebapppod
        labels:
          app: javawebapp
      spec:
        containers:
        - name: javawebapp
          image: dockerhandson/java-web-app:2
          ports:
          - containerPort: 8080
          resources:
             requests:
               cpu: 100m
               memory: 128Mi
             limits:
                cpu: 1
                memory: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
