apiVersion: v1
kind: ReplicationController
metadata:
   name: pythonrc
spec:
  replicas: 1
  template: # pod template
    metadata:
      name: pythonapppod
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonappcontainer
        image: dockerhandson/python-app:1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: pythonappsvc
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - port: 80
      targetPort: 5000

