apiVersion: v1
kind: ResourceQuota
metadata:
   name: testns-qs-quota
   namespace: test-ns
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: 3
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: test-ns
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container    
